### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by EvgeniyRub** [Skitionek/notify-microsoft-teams#41]
Got an warning in Github actions: "Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: skitionek/notify-microsoft-teams@master"

Anybody knows how to fix this?

**Comment by aabeling** [comment]
I just tried it: https://github.com/aabeling/notify-microsoft-teams/tree/node16
All I did was to update the `action.yml`.
It worked with a private repo by using `aabeling/notify-microsoft-teams@node16`.

But I can't give any guarantee that it works with every possible configuration.

**Comment by mvanvendeloo** [comment]
@Skitionek Could you merge this pull request? Soon the support for node12 will be deprecated!

**Comment by kushal-omnius** [comment]
F

**Comment by Skitionek** [comment]
Updated to node 16 🎉
Please let me know if it caused any issues
