### ISSUE TITLE
How to pass a different jobs context into the action?

### ISSUE THREAD

**Issue by UdaySamineni** [Skitionek/notify-microsoft-teams#67]
My workflow has two jobs. Job one handles build steps. Job two is exception handling, which only triggers if job one fails on any of the steps. I have integrated the notify-microsoft-teams action under job two as a new step to receive Teams messages whenever there is an exception. The notify-microsoft-teams action takes the current job context (job two in this case) to display the status summary. Suppose there is an exception in job one. In that case, we can log all the job information using the "needs summary" but the final status summary is always success/green if the job where the notify-microsoft-teams action is running is successful. 

If you look at the below screenshot, the status summary is successful even though there are failures in the "needs summary" because the notify-microsoft-teams action looks at the current job status to display status summary information. The action works fine if everything is under one job. 

Can we send another job's context (job one in this case) as a parameter, so that the notify-microsoft-teams action can display that job status summary? 

![My Teams Message ](https://user-images.githubusercontent.com/26513321/219799320-02baa25b-df5b-40d2-91b9-48cc71e6e274.png)

**Comment by UdaySamineni** [comment]
I can output job one's job status using the `output ` and access job one's status in job two using `needs`. Finally instead of using the default `job: ${{ toJson(job) }}` in the teams' action - which passes the current job context - I override it with the job one status.

**Comment by rijami00** [comment]
@UdaySamineni  can you give an example of what you did?
